<?php
/**
 * DisbursementDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FayaPay API
 *
 * FayaPay API
 *
 * OpenAPI spec version: 1
 * Contact: support@fayapay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FayaPay;

/**
 * DisbursementDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description DisbursementDTO
/**
 * @package     FayaPay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DisbursementDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DisbursementDTO"
     */
    public function testDisbursementDTO()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "recipient_name"
     */
    public function testPropertyRecipientName()
    {
    }

    /**
     * Test attribute "recipient_email"
     */
    public function testPropertyRecipientEmail()
    {
    }

    /**
     * Test attribute "recipient_account_provider"
     */
    public function testPropertyRecipientAccountProvider()
    {
    }

    /**
     * Test attribute "recipient_account_number"
     */
    public function testPropertyRecipientAccountNumber()
    {
    }

    /**
     * Test attribute "recipient_account_country"
     */
    public function testPropertyRecipientAccountCountry()
    {
    }

    /**
     * Test attribute "statement_descriptor"
     */
    public function testPropertyStatementDescriptor()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "paid"
     */
    public function testPropertyPaid()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "receipt_id"
     */
    public function testPropertyReceiptId()
    {
    }

    /**
     * Test attribute "receipt_email"
     */
    public function testPropertyReceiptEmail()
    {
    }

    /**
     * Test attribute "receipt_phone"
     */
    public function testPropertyReceiptPhone()
    {
    }

    /**
     * Test attribute "failure_message"
     */
    public function testPropertyFailureMessage()
    {
    }

    /**
     * Test attribute "livemode"
     */
    public function testPropertyLivemode()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }
}
