<?php
/**
 * CustomersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FayaPay API
 *
 * API Reference for FayaPay
 *
 * OpenAPI spec version: 1
 * Contact: support@fayapay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace FayaPay;

use \FayaPay\Configuration;
use \FayaPay\ApiException;
use \FayaPay\ObjectSerializer;

/**
 * CustomersApiTest Class Doc Comment
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for attachSource
     *
     * Attach a source to a customer.
     *
     */
    public function testAttachSource()
    {
    }

    /**
     * Test case for createCustomer
     *
     * Create a Customer.
     *
     */
    public function testCreateCustomer()
    {
    }

    /**
     * Test case for fetchCustomer
     *
     * Fetch a Customer.
     *
     */
    public function testFetchCustomer()
    {
    }

    /**
     * Test case for listCustomers
     *
     * List Customers.
     *
     */
    public function testListCustomers()
    {
    }

    /**
     * Test case for updateCustomer
     *
     * Update a Customer.
     *
     */
    public function testUpdateCustomer()
    {
    }
}
