<?php
/**
 * RefundsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FayaPay API
 *
 * API Reference for FayaPay
 *
 * OpenAPI spec version: 1
 * Contact: support@fayapay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace FayaPay;

use \FayaPay\Configuration;
use \FayaPay\ApiException;
use \FayaPay\ObjectSerializer;

/**
 * RefundsApiTest Class Doc Comment
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RefundsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fetchRefund
     *
     * Fetch a Refund.
     *
     */
    public function testFetchRefund()
    {
    }

    /**
     * Test case for listRefunds
     *
     * List Refunds.
     *
     */
    public function testListRefunds()
    {
    }

    /**
     * Test case for updateRefund
     *
     * Update a Refund.
     *
     */
    public function testUpdateRefund()
    {
    }
}
