<?php
/**
 * DisbursementFailureCodeValue
 *
 * PHP version 5
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FayaPay API
 *
 * FayaPay API
 *
 * OpenAPI spec version: 1
 * Contact: support@fayapay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FayaPay\Model;
use \FayaPay\ObjectSerializer;

/**
 * DisbursementFailureCodeValue Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DisbursementFailureCodeValue
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const GATEWAY_ERROR = 'GatewayError';
    const INSUFFICIENT_BALANCE = 'InsufficientBalance';
    const TIMED_OUT = 'TimedOut';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::GATEWAY_ERROR,
            self::INSUFFICIENT_BALANCE,
            self::TIMED_OUT,
        ];
    }
}


