<?php
/**
 * ListResponseOfCustomerDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FayaPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FayaPay API
 *
 * API Reference for FayaPay
 *
 * OpenAPI spec version: 1
 * Contact: support@fayapay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FayaPay;

/**
 * ListResponseOfCustomerDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description ListResponseOfCustomerDTO
/**
 * @package     FayaPay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListResponseOfCustomerDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListResponseOfCustomerDTO"
     */
    public function testListResponseOfCustomerDTO()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "next_cursor"
     */
    public function testPropertyNextCursor()
    {
    }

    /**
     * Test attribute "previous_cursor"
     */
    public function testPropertyPreviousCursor()
    {
    }
}
